version: '3'
services:
  jupyter:
    build: jupyterdemo/.
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
  searchapi:
    environment:
      - PORT=5001
    build: searchapi/.
    ports:
      - "5001:5001"
  react:
    tty: true
    build: frontend/.
    ports:
      - "3000:3000"
