version: '3'
services:
  # jupyter:
  #   build: jupyterdemo/.
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
  searchapi:
    environment:
      - PORT=5001
    build: searchapi/.
    ports:
      - "5001:5001"
  express:
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://db:27017
      - SECRET=sekret
      - CLIENT_SECRET=68a35b11cf04cc4acb9c11828e97b4d1e7463418
      - CLIENT_ID=Iv1.b17443d260d190ec
    build: express/.
    ports:
      - "5000:5000"
  # react:
  #   environment:
  #     - REACT_APP_EXPRESS=http://localhost:5000/
  #     - REACT_APP_SEARCHAPI=http://localhost:5001/api/
  #   build: react/.
  #   ports:
  #     - "3000:3000"
