version: '3'
services:
  db:
    image: 'mongo'
    ports: 
      - "27017:27017"
  
  express:
    environment:
      - DATABASE_URL=mongodb://db:27017
      - PORT=5000
      - SECRET=sekret
    build: express/.
    ports:
      - "5000:5000"

  react:
    environment:
      - REACT_APP_AUTH=http://localhost:5000/auth
      - REACT_APP_API=http://localhost:5000
      - REACT_APP_BACKEND=http://localhost:5000/
    build: react/.
    ports:
      - "3000:3000"

    